channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - docopt
  - snakemake
  - bioconda::salmon=1.10.1
  - git
  - pip:
      - git+https://github.com/hyunhwaj/SalmonTE.git
